# Ames Housing ML Challenge

# Linear Modeling

In [41]:
import pandas as pd
import numpy as np

In [42]:
housing_train = pd.read_csv('housing_train.csv')
housing_test = pd.read_csv('housing_test.csv')

y_housing = pd.read_csv('y_housing.csv')

In [23]:
housing_test.head()

,MSSubClass,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtUnfSF,TotalBsmtSF,2ndFlrSF,...,SaleType_5,SaleType_6,SaleType_7,SaleType_8,SaleCondition_1,SaleCondition_2,SaleCondition_3,SaleCondition_4,SaleCondition_5,Id
0,-1.153717,0.0,-0.750032,0.391824,-0.333148,-1.091311,-0.796103,-0.653512,-0.360330,-0.780237,...,0,0,0,1,0,0,0,1,0,1461
1,-1.153717,0.0,-0.020243,0.391824,-0.432720,-1.234273,1.162044,-0.338164,0.729540,-0.780237,...,0,0,0,1,0,0,0,1,0,1462
2,0.491058,0.0,-0.750032,-0.509820,0.861722,0.671883,-0.796103,-0.961904,-0.248173,0.934863,...,0,0,0,1,0,0,0,1,0,1463
3,0.491058,0.0,-0.020243,0.391824,0.894913,0.671883,0.737189,-0.528300,-0.253050,0.878590,...,0,0,0,1,0,0,0,1,0,1464
4,1.346030,0.0,1.439335,-0.509820,0.695768,0.385959,-0.796103,1.078582,0.610069,-0.780237,...,0,0,0,1,0,0,0,1,0,1465

In [43]:
print('Full Train dimension:', housing_train.shape)
print('Y train dimension:', y_housing.shape)
print('Test data dimension:', housing_test.shape)

Full Train dimension: (1353, 243)
Y train dimension: (1353, 1)
Test data dimension: (1459, 243)

In [44]:
from sklearn import linear_model
from sklearn.linear_model import ElasticNet, Lasso, Ridge, SGDRegressor
from sklearn.ensemble import RandomForestRegressor,  GradientBoostingRegressor
from sklearn.kernel_ridge import KernelRidge
from sklearn.base import BaseEstimator, TransformerMixin, RegressorMixin, clone
from sklearn.model_selection import  train_test_split
from sklearn.metrics import mean_squared_error, log_loss
from sklearn.decomposition import PCA



import sklearn.model_selection as ms

from sklearn import ensemble
from sklearn.ensemble import RandomForestRegressor
from pprint import pprint
from sklearn.svm import SVR

In [45]:
X_train, X_test, y_train, y_test = train_test_split(housing_train, y_housing, test_size = 0.30, random_state = 42)

In [46]:
ridge = linear_model.Ridge(alpha = 25, normalize=False, copy_X= True, fit_intercept = True)
lasso = linear_model.Lasso(alpha= 0, normalize = True)
elasticnet = linear_model.ElasticNet(alpha = 0.01, l1_ratio=0.5, normalize=False)
clf = linear_model.SGDRegressor(max_iter=1000, tol=1e-3)

gbm = ensemble.GradientBoostingRegressor()
rf = ensemble.RandomForestRegressor(n_estimators = 400, min_samples_split=2,
                                    min_samples_leaf = 1, max_features = 'sqrt',
                                    max_depth = None, bootstrap = False, random_state=42)

In [122]:
Parameters currently in use:

{'alpha': 1,
 'copy_X': True,
 'fit_intercept': True,
 'max_iter': None,
 'normalize': True,
 'random_state': None,
 'solver': 'auto',
 'tol': 0.001}

SyntaxError: invalid syntax (<ipython-input-122-9cd7b7c62ae1>, line 1)

In [28]:
housing_train.shape

(1353, 243)

In [9]:
y_housing.shape

(1353, 1)

In [47]:
modelList =[ridge, lasso, elasticnet, clf, gbm, rf]
modelSeries= pd.Series(modelList, index =[ 'Ridge', 'Lasso', 'Elasticnet', 'SGD', 'XGboost', 'Random Forest'])

In [48]:
modelSeries.apply(lambda x:x.fit(X_train, y_train))

/Users/lauraelliott/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: With alpha=0, this algorithm does not converge well. You are advised to use the LinearRegression estimator
  """Entry point for launching an IPython kernel.
/Users/lauraelliott/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/coordinate_descent.py:478: UserWarning: Coordinate descent with no regularization may lead to unexpected results and is discouraged.
  positive)
/Users/lauraelliott/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/coordinate_descent.py:492: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Fitting data with very small alpha may cause precision problems.
  ConvergenceWarning)
/Users/lauraelliott/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/lauraelliott/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/lauraelliott/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.

Ridge            Ridge(alpha=25, copy_X=True, fit_intercept=Tru...
Lasso            Lasso(alpha=0, copy_X=True, fit_intercept=True...
Elasticnet       ElasticNet(alpha=0.01, copy_X=True, fit_interc...
SGD              SGDRegressor(alpha=0.0001, average=False, earl...
XGboost          ([DecisionTreeRegressor(criterion='friedman_ms...
Random Forest    (DecisionTreeRegressor(criterion='mse', max_de...
dtype: object

In [49]:
ans = pd.concat([modelSeries.apply(lambda x: x.score(X_train,y_train)),modelSeries.apply(lambda x: x.score(X_test,y_test)), 
                                    modelSeries.apply(lambda x: np.sqrt(mean_squared_error(x.predict(X_test), y_test)))],axis=1)

ans.columns = ['train score', 'test score', 'rmse']
ans

                train score    test score          rmse
Ridge          9.181371e-01  9.105501e-01  1.073988e-01
Lasso          9.426321e-01  8.744614e-01  1.272325e-01
Elasticnet     8.800992e-01  8.875909e-01  1.203954e-01
SGD           -1.179961e+29 -1.164629e+29  1.225471e+14
XGboost        9.550343e-01  8.737442e-01  1.275954e-01
Random Forest  1.000000e+00  8.754064e-01  1.267527e-01

## Prediction

In [50]:
test = pd.read_csv('test.csv')

In [51]:
import math

housing_test['SalePrice'] = ridge.predict(housing_test)

In [52]:
housing_test.head()

,MSSubClass,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtUnfSF,TotalBsmtSF,2ndFlrSF,...,SaleType_6,SaleType_7,SaleType_8,SaleCondition_1,SaleCondition_2,SaleCondition_3,SaleCondition_4,SaleCondition_5,Id,SalePrice
0,-1.153717,0.0,-0.750032,0.391824,-0.333148,-1.091311,-0.796103,-0.653512,-0.360330,-0.780237,...,0,0,1,0,0,0,1,0,1461,11.670258
1,-1.153717,0.0,-0.020243,0.391824,-0.432720,-1.234273,1.162044,-0.338164,0.729540,-0.780237,...,0,0,1,0,0,0,1,0,1462,11.929475
2,0.491058,0.0,-0.750032,-0.509820,0.861722,0.671883,-0.796103,-0.961904,-0.248173,0.934863,...,0,0,1,0,0,0,1,0,1463,12.094438
3,0.491058,0.0,-0.020243,0.391824,0.894913,0.671883,0.737189,-0.528300,-0.253050,0.878590,...,0,0,1,0,0,0,1,0,1464,12.192308
4,1.346030,0.0,1.439335,-0.509820,0.695768,0.385959,-0.796103,1.078582,0.610069,-0.780237,...,0,0,1,0,0,0,1,0,1465,12.121099

In [53]:
housing_test['SalePrice'] = housing_test['SalePrice'] .apply(lambda x: math.exp(x))

In [54]:
housing_test.head()

,MSSubClass,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtUnfSF,TotalBsmtSF,2ndFlrSF,...,SaleType_6,SaleType_7,SaleType_8,SaleCondition_1,SaleCondition_2,SaleCondition_3,SaleCondition_4,SaleCondition_5,Id,SalePrice
0,-1.153717,0.0,-0.750032,0.391824,-0.333148,-1.091311,-0.796103,-0.653512,-0.360330,-0.780237,...,0,0,1,0,0,0,1,0,1461,117038.489259
1,-1.153717,0.0,-0.020243,0.391824,-0.432720,-1.234273,1.162044,-0.338164,0.729540,-0.780237,...,0,0,1,0,0,0,1,0,1462,151671.924541
2,0.491058,0.0,-0.750032,-0.509820,0.861722,0.671883,-0.796103,-0.961904,-0.248173,0.934863,...,0,0,1,0,0,0,1,0,1463,178874.118109
3,0.491058,0.0,-0.020243,0.391824,0.894913,0.671883,0.737189,-0.528300,-0.253050,0.878590,...,0,0,1,0,0,0,1,0,1464,197266.024801
4,1.346030,0.0,1.439335,-0.509820,0.695768,0.385959,-0.796103,1.078582,0.610069,-0.780237,...,0,0,1,0,0,0,1,0,1465,183707.241059

In [55]:
submission =housing_test[['Id', 'SalePrice']].sort_values(ascending = True, by ='Id')

In [56]:
submission.head()

     Id      SalePrice
0  1461  117038.489259
1  1462  151671.924541
2  1463  178874.118109
3  1464  197266.024801
4  1465  183707.241059

In [57]:
submission.to_csv('submission.csv', index = False)

In [ ]:
#############################################################################################################

In [ ]:
###################################################################################################################